apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq-ha.fullname" . }}
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    loadbalancer.alauda.io/bind: '[{"container_port": {{ .Values.rabbitmqManagerPort }}, "protocol": "tcp", "name": "{{ .Values.lb.load_balance_name }}", "port": {{ .Values.lb.rabbitmqManagerPort }}},{"container_port": {{ .Values.rabbitmqNodePort }}, "protocol": "tcp", "name": "{{ .Values.lb.load_balance_name }}", "port": {{ .Values.lb.rabbitmqNodePort }}},{"container_port": {{ .Values.rabbitmqEpmdPort }}, "protocol": "tcp", "name": "{{ .Values.lb.load_balance_name }}", "port": {{ .Values.lb.rabbitmqEpmdPort }}}]'
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.rabbitmqManagerPort }}
      targetPort: http
    - name: amqp
      protocol: TCP
      port: {{ .Values.rabbitmqNodePort }}
      targetPort: amqp
    - name: epmd
      protocol: TCP
      port: {{ .Values.rabbitmqEpmdPort }}
      targetPort: epmd
    {{- if .Values.rabbitmqAmqpsSupport.enabled }}
    - name: amqps
      protocol: TCP
      port: {{ .Values.rabbitmqAmqpsSupport.amqpsNodePort }}
      targetPort: amqps
    {{- end }}
  selector:
    app: {{ template "rabbitmq-ha.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
