apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "config-server.fullname" . }}-{{ .Release.Namespace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "config-server.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "config-server.fullname" . }}-{{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: {{ template "config-server.fullname" . }}-{{ .Release.Namespace }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        releaseRevision: "{{ .Release.Revision }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - env:
        - name: ALAUDA_CONFIG_SERVER_RULE
          value: {{ b64enc .Values.rule }}
        - name: ALAUDA_SERVER_PORT
          value: "{{ .Values.port }}"
        - name: ALAUDA_KAFKA_INFO
          value: {{ .Values.kafkaEndpoint }}
        - name: ALAUDA_ZOOKEEPER_INFO
          value: "{{.Values.zookeeperEndpoint}}"
        image: "{{ .Values.registryAddress }}/claas/config-server:v0.0.1"
        name: config-server
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}