apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hbase.fullname" . }}-{{ index .Values "metadata" "k8sResourceName" "core-cm" }} 
data:
  SERVICES: hbase
  GROUP: core 
  GROUP_ROLE: core
  COMPONENT: hr
  
#---  
#rsion: policy/v1beta1
# PodDisruptionBudget
#ata:
#e: {{ template "hbase.fullname" . }}-{{ index .Values "metadata" "k8sResourceName" "core-pdb"}}
#
#ector:
#atchLabels:
# vender: {{ .Values.metadata.vendor }}
# app: {{ template "hbase.fullname" . }}-{{ .Values.metadata.k8sResourceName.core}}
# chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
# release: {{ .Release.Name }} 
#Unavailable: {{ .Values.corePod.pdbMinAvailable }}
---  
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hbase.fullname" . }}-{{ index .Values "metadata" "k8sResourceName" "core-svc"}}
  labels:
    vender: {{ .Values.metadata.vendor }}
    app: {{ template "hbase.name" . }}-{{ .Values.metadata.k8sResourceName.core}}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  {{- range $key, $val := .Values.corePod.port }}
  - name: {{ $key }}
    port: {{ $val }}
  {{- end }}
  clusterIP: None
  selector:
    vender: {{ .Values.metadata.vendor }}
    app: {{ template "hbase.fullname" . }}-{{ .Values.metadata.k8sResourceName.core}} 
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "hbase.fullname" . }}-{{ .Values.metadata.k8sResourceName.core}}
spec:
  serviceName: {{ template "hbase.fullname" . }}-{{ index .Values "metadata" "k8sResourceName" "core-svc"}}
  replicas: {{ .Values.corePod.replicas }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        vender: {{ .Values.metadata.vendor }}
        app: {{ template "hbase.fullname" . }}-{{ .Values.metadata.k8sResourceName.core}} 
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }} 
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - {{ template "hbase.fullname" . }}-{{ .Values.metadata.k8sResourceName.core}} 
                    - {{ template "hbase.fullname" . }}-{{ .Values.metadata.k8sResourceName.master}} 
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ template "hbase.fullname" . }}-{{ .Values.metadata.k8sResourceName.core}} 
        imagePullPolicy: Always
        image: {{ .Values.registryAddress }}{{- template "image.repository.part" . -}}:{{- template "image.tag" . }}
        resources:
          requests:
            memory: {{ .Values.corePod.resources.requests.memory}} 
            cpu: {{ .Values.corePod.resources.requests.cpu}}
          limits:
            memory: {{ .Values.corePod.resources.limits.memory}} 
            cpu: {{ .Values.corePod.resources.limits.cpu}}
        ports:
        {{- range $key, $val := .Values.corePod.port }}
        - containerPort: {{ $val }}
        {{- end }}
        
        command:
        - sh
        - -c
        - {{ if .Values.hadoop.ready -}}
           "cp /tmp/hadoop-config/bootstrap.sh /usr/local/bin/bootstrap.sh && chmod 755 /usr/local/bin/bootstrap.sh && /usr/local/bin/bootstrap.sh && \
          {{- else -}}
           "\
          {{- end }}
          {{ if .Values.injectCfgFiles.enabled -}}
            cp /tmp/hadoop-config/bootstrap.sh /usr/local/bin/bootstrap.sh && chmod 755 /usr/local/bin/bootstrap.sh && /usr/local/bin/bootstrap.sh && /opt/alauda/sbin/startup.sh"
          {{- else -}}
            /opt/alauda/sbin/startup.sh"
          {{- end }}
        envFrom:
        - configMapRef:
            name: {{ template "hbase.fullname" . }}-{{index .Values "metadata" "k8sResourceName" "core-cm"}}
        volumeMounts:
        - name: datadir
          mountPath: {{ .Values.corePod.mountPath }}
        {{- if .Values.injectCfgFiles.enabled }}
        - mountPath: /tmp/hbase-config/bootstrap.sh
          name: config-files
          subPath: bootstrap.sh
        - mountPath: {{ .Values.injectCfgFiles.cfgMountPath }}/conf/hbase-site.xml
          name: config-files
          subPath: hbase-site.xml
        {{- end }}
        {{- if .Values.hadoop.ready }}
        - name: hadoop-config
          mountPath: /tmp/hadoop-config
        {{- end }}
      
      volumes:
      {{- if .Values.injectCfgFiles.enabled }}
      - name: config-files
        configMap: 
          {{- if or (eq "" .Values.injectCfgFiles.configMapName ) (eq "-" .Values.injectCfgFiles.configMapName ) }}
          name: {{ template "hbase.fullname" . }}-{{ index .Values "metadata" "k8sResourceName" "config-files" }} 
          {{- else }}
          name: {{ .Values.injectCfgFiles.configMapName }}
          {{- end }}
      {{- end }}
      {{- if eq .Values.corePod.persistence.enabled false }}
      - name: datadir
        emptyDir: {}
      {{- end }}
      {{- if .Values.hadoop.ready }}
      - name: hadoop-config
        configMap: 
          name: {{ index .Values "hadoop" "configMapName"}}
      {{- end }}

{{- if .Values.corePod.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ {{ .Values.corePod.persistence.accessMode }} ]
      resources:
        requests:
          storage: {{ .Values.corePod.persistence.size }}
      {{- if .Values.corePod.persistence.storageClass }}
      {{- if (eq "-" .Values.corePod.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: {{ .Values.corePod.persistence.storageClass | quote }}
      {{- end }}
      {{- end }}
{{- end -}}    