apiVersion: v1
kind: Service
metadata:
  {{ if and .Values.loadbalancerName .Values.loadbalancerPort }}
  annotations:
    loadbalancer.alauda.io/bind: '[{"container_port":{{.Values.port}},"protocol":"http","name":"{{.Values.loadbalancerName}}","port":{{.Values.loadbalancerPort}}}]'
  {{ end }}
  namespace: {{ .Release.Namespace }}
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}-{{ .Release.Namespace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: eureka
    port: {{ .Values.port }}
  selector:
    app: {{ template "fullname" . }}-{{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "fullname" . }}-headless
  labels:
    app: {{ template "fullname" . }}-{{ .Release.Namespace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: eureka
    port: {{ .Values.port }}
  clusterIP: None
  selector:
    app: {{ template "fullname" . }}-{{ .Release.Namespace }}
  type: ClusterIP